---
title: "Visualisations"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#install.packages("rnaturalearth")

#library(leaflet)
#library(rnaturalearth)
```

<head>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>

```{r, echo=FALSE}
#world <- ne_countries(scale = "medium", returnclass = "sf")

#UK <-world[world$name == "United Kingdom",]
#USA <-world[world$admin == "United States of America",]
#NZ <- world[world$name == "New Zealand",]
#AU <- world[world$name == "Australia",]
#CA <- world[world$name == "Canada",]

#whole <- rbind(UK,USA,NZ,AU,CA)
#whole$people_count <- c(1,1,1,3,2)
#whole$cus_abbr <- c("UK","USA","NZ","AU","CA")

#palette <- colorNumeric(palette = "YIOrRd", domain = whole$people_count)

#leaflet(whole) %>% addTiles() %>% 
#  addMarkers(lng = ~label_x, lat = ~label_y, popup = ~paste(cus_abbr,":",people_count)) %>% 
#  addPolygons(fillColor = ~palette(people_count), fillOpacity = 0.7,stroke = FALSE)
```